name: Build

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - run: cd influencers-ui && npm install
      - run: cd influencers-ui && npm test
      - run: export NODE_OPTIONS="--openssl-legacy-provider" && cd influencers-ui && npm run build

      - name: Set up Docker Buildx
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ARTIFACTORY_HOST }}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Build the Docker image
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: docker build . --file Dockerfile --tag ${{ secrets.ARTIFACTORY_HOST }}/cst-docker-dev/influencers-ui-github:${{  github.ref_name }}

      - name: Push Docker Image
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: docker push ${{ secrets.ARTIFACTORY_HOST }}/cst-docker-dev/influencers-ui-github:${{  github.ref_name }}

      - name: Upload to S3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: |
          aws s3 sync influencers-ui/build/ s3://react-app-bucket-pmi/